#!/usr/bin/env sh
# Copyright (c) 2022 Operator
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

if [ "update" = $1 ]; then
    echo "krun update!"
    curl -o /usr/bin/krun https://raw.githubusercontent.com/kevin197011/sh/main/krun && chmod +x /usr/bin/krun
    exit 0
fi

if [ "list" = $1 ]; then
  echo "shell name list:"
  curl https://github.com/kevin197011/sh/tree/main/lib | grep -Eo '[a-zA-Z0-9-]+\.sh' | uniq | sed 's/.sh//g'
  exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/kevin197011/sh/main/lib/$1.sh)"
