#!/usr/bin/env bash
# Copyright (c) 2022 Operator
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# update
if [[ "update" = $1 ]]; then
    echo "[INFO] krun update!"
    curl -s https://raw.githubusercontent.com/kevin197011/sh/main/krun >/usr/bin/krun && chmod +x /usr/bin/krun
    exit 0
fi

# custom config first
custom_config='/etc/krun/config.sh'
[[ -d /etc/krun ]] || mkdir -p /etc/krun
[[ -f ${custom_config} ]] || echo 'github_repo_name=""' >${custom_config}

# import config
source ${custom_config}

# list script
if [[ "list" = $1 ]]; then
    echo "[INFO] script list:"
    [[ ! -z "${github_repo_name}" ]] && github_repo="https://github.com/${github_repo_name}/sh-libs/tree/main" || \
    github_repo="https://github.com/kevin197011/sh/tree/main/lib"
    curl -s ${github_repo} | grep -Eo '[a-zA-Z0-9-]+\.(sh|pl|py|rb)' | uniq | sed 's/^/- /g'
    exit 0
fi

# tmp download run
cd /tmp

[[ ! -z "${github_repo_name}" ]] && github_repo_sh="https://raw.githubusercontent.com/${github_repo_name}/sh-libs/main" || \
github_repo_sh="https://raw.githubusercontent.com/kevin197011/sh/main/lib"

curl -s -o $1 ${github_repo_sh}/$1

# hashmap
declare -A file_map
file_map["sh"]="sh"
file_map["rb"]="ruby"
file_map["py"]="python"
file_map["pl"]="perl"

if [[ "debug" = $2 ]]; then
    cat $1 && exit 0
fi

${file_map["${1##*.}"]} $1

# status
if [[ "status" = $1 ]]; then
    echo "[INFO] krun ready!"
    exit 0
fi

# end detele script file
rm -rf $1

# uninstall krun
if [[ "uninstall" = $1 ]]; then
    echo "[INFO] krun uninstall!"
    rm -rf /usr/local/bin/krun
    rm -rf /etc/krun/config.sh
fi
